import { client, isAmplifyConfigured } from './amplifyConfig.js';

// GraphQL operations (will be auto-generated by Amplify)
const createLevelMutation = /* GraphQL */ `
  mutation CreateLevel($input: CreateLevelInput!) {
    createLevel(input: $input) {
      id
      name
      description
      authorName
      accel
      rollingResistance
      brakeDecel
      initialSpeed
      backgroundColor
      groundColor
      elevationProfile
      slopeZones
      playCount
      createdAt
    }
  }
`;

const listLevelsQuery = /* GraphQL */ `
  query ListLevels($limit: Int) {
    listLevels(limit: $limit) {
      items {
        id
        name
        description
        authorName
        accel
        rollingResistance
        brakeDecel
        initialSpeed
        backgroundColor
        groundColor
        elevationProfile
        slopeZones
        playCount
        createdAt
      }
    }
  }
`;

const updateLevelMutation = /* GraphQL */ `
  mutation UpdateLevel($input: UpdateLevelInput!) {
    updateLevel(input: $input) {
      id
      playCount
    }
  }
`;

// Local storage fallback key
const LOCAL_LEVELS_KEY = 'planetStopCustomLevels';

// Get levels from local storage (fallback)
function getLocalLevels() {
  try {
    const data = localStorage.getItem(LOCAL_LEVELS_KEY);
    return data ? JSON.parse(data) : [];
  } catch {
    return [];
  }
}

// Save levels to local storage (fallback)
function saveLocalLevels(levels) {
  localStorage.setItem(LOCAL_LEVELS_KEY, JSON.stringify(levels));
}

// Create a new level
export async function saveLevel(levelData) {
  const input = {
    name: levelData.name,
    description: levelData.description || '',
    authorName: levelData.authorName || 'Anonymous',
    accel: levelData.accel,
    rollingResistance: levelData.rollingResistance,
    brakeDecel: levelData.brakeDecel,
    initialSpeed: levelData.initialSpeed,
    backgroundColor: levelData.backgroundColor,
    groundColor: levelData.groundColor,
    elevationProfile: JSON.stringify(levelData.elevationProfile),
    slopeZones: JSON.stringify(levelData.slopeZones),
    playCount: 0
  };

  if (isAmplifyConfigured && client) {
    try {
      const result = await client.graphql({
        query: createLevelMutation,
        variables: { input }
      });
      return result.data.createLevel;
    } catch (error) {
      console.error('Failed to save to Amplify:', error);
      throw error;
    }
  } else {
    // Local storage fallback
    const levels = getLocalLevels();
    const newLevel = {
      ...input,
      id: `local_${Date.now()}`,
      createdAt: new Date().toISOString(),
      elevationProfile: levelData.elevationProfile,
      slopeZones: levelData.slopeZones
    };
    levels.unshift(newLevel);
    saveLocalLevels(levels);
    return newLevel;
  }
}

// Fetch all levels with sorting
export async function fetchLevels(sortBy = 'newest', limit = 50) {
  let levels = [];

  if (isAmplifyConfigured && client) {
    try {
      const result = await client.graphql({
        query: listLevelsQuery,
        variables: { limit }
      });
      levels = result.data.listLevels.items.map(level => ({
        ...level,
        elevationProfile: JSON.parse(level.elevationProfile),
        slopeZones: JSON.parse(level.slopeZones)
      }));
    } catch (error) {
      console.error('Failed to fetch from Amplify:', error);
      levels = getLocalLevels();
    }
  } else {
    // Local storage fallback
    levels = getLocalLevels();
  }

  // Client-side sorting
  if (sortBy === 'newest') {
    levels.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  } else if (sortBy === 'popular') {
    levels.sort((a, b) => (b.playCount || 0) - (a.playCount || 0));
  }

  return levels;
}

// Increment play count
export async function incrementPlayCount(id, currentCount) {
  if (isAmplifyConfigured && client) {
    try {
      await client.graphql({
        query: updateLevelMutation,
        variables: {
          input: {
            id,
            playCount: (currentCount || 0) + 1
          }
        }
      });
    } catch (error) {
      console.error('Failed to update play count:', error);
    }
  } else {
    // Local storage fallback
    const levels = getLocalLevels();
    const level = levels.find(l => l.id === id);
    if (level) {
      level.playCount = (level.playCount || 0) + 1;
      saveLocalLevels(levels);
    }
  }
}
